"""Admin handlers package - split for maintainability."""

from handlers.admin.panel import *
from handlers.admin.scholars import *
from handlers.admin.podcast import *
from handlers.admin.subscribers import *
from handlers.admin.categories import *
from handlers.admin.stats import *
from handlers.admin.sources import *
from handlers.admin.settings import *

# Explicit exports for backward compatibility
__all__ = [
    "admin_conv",
    "admin_panel",
    "apply_weekly_day",
    "backup_database_handler",
    "cancel_category_search_admin",
    "cancel_podcast_broadcast",
    "category_conv",
    "cleanup_inactive_subscribers",
    "confirm_delete_category_handler",
    "confirm_delete_source",
    "confirm_delete_topic_handler",
    "confirm_scholar_bio",
    "delete_category_handler",
    "delete_podcast_broadcast",
    "delete_source_handler",
    "delete_topic_handler",
    "handle_category_type_filter",
    "handle_settings_time_input",
    "list_admins_handler",
    "manage_admins",
    "manage_categories",
    "manage_links_panel",
    "manage_scholars_panel",
    "manage_source",
    "manage_sources",
    "manage_subscribers",
    "manage_topic_handler",
    "podcast_conv",
    "podcast_panel",
    "receive_admin_id",
    "receive_category_search_term",
    "receive_daily_time",
    "receive_edit_category_name",
    "receive_edit_source",
    "receive_edit_topic_name",
    "receive_new_category",
    "receive_new_scholar_admin",
    "receive_new_source",
    "receive_new_topic",
    "receive_podcast_content",
    "receive_podcast_edit",
    "receive_scholar_bio",
    "receive_scholar_website",
    "receive_weekly_time",
    "scholar_conv",
    "settings_conv",
    "settings_panel",
    "show_admin_drafts",
    "show_duplicates",
    "show_missing_links",
    "show_scholars_admin",
    "show_statistics",
    "source_conv",
    "start_add_category_admin",
    "start_add_scholar_admin",
    "start_add_scholar_bio",
    "start_add_source",
    "start_add_topic_admin",
    "start_edit_category_name",
    "start_edit_podcast_broadcast",
    "start_edit_source",
    "start_edit_topic_admin",
    "start_remove_admin",
    "start_set_daily_time",
    "start_set_weekly_day",
    "start_set_weekly_time",
    "test_notify",
    "toggle_maintenance_mode",
    "topic_conv",
    "view_scholar_admin",
    "view_topics_handler",
    "_WEEKDAYS_AR",
]
